import type { Metadata } from "next";
import {
  Danfo,
  Geist,
  Geist_Mono,
  Rubik,
  Mochiy_Pop_One,
  Rubik_Glitch_Pop,
} from "next/font/google";
import "./globals.css";
import Navbar from "../components/Utilities/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const danfo = Danfo({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-danfo",
  display: "swap",
});

const mochiyPop = Mochiy_Pop_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-mochiy-pop",
  display: "swap",
});

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
  display: "swap",
});

const rubikGlitch = Rubik_Glitch_Pop({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-rubik-glitch",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${danfo.variable}  
          ${mochiyPop.variable}  
          ${rubik.variable}
          ${rubikGlitch.variable}
          antialiased
        `}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
